services:
    SyncFbPageService:
        class:  Mnemono\BackgroundServiceBundle\Services\SyncFbPageService
        arguments:  [ @service_container ]
    SyncFbFeedService:
        class:  Mnemono\BackgroundServiceBundle\Services\SyncFbFeedService
        arguments:  [ @service_container ]
    PostScoreService:
        class:  Mnemono\BackgroundServiceBundle\Services\PostScoreService
        arguments:  [ @service_container ]
