coding_guys_cms:
    resource: "@CodingGuysCMSBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation

fos_comment_api:
    type: rest
    resource: @FOSCommentBundle/Resources/config/routing.yml
    prefix: /api
    defaults: { _format: html }

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"