security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false

        secured_area:
            pattern:    ^/demo/secured/
            form_login:
                check_path: _security_check
                login_path: _demo_login
            logout:
                path:   _demo_logout
                target: _demo
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

        main:
            pattern: ^/cms
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: @loginPage
                check_path: fos_user_security_check
                default_target_path:   @BackendHome
                target_path_parameter: _target_path
            logout:
                path:   fos_user_security_logout
                target: @loginPage
            anonymous:    true
        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

        oauth_authorize:
            pattern:    ^/oauth/v2/auth
            anonymous: true
            # Add your favorite authentication process here

        api:
            pattern:    ^/api/mobile/
            fos_oauth:  true
            stateless:  true
            anonymous:  false # can be omitted as its default value

    access_control:
        #- { path: ^/cms/user/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/cms/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/cms/user/register/confirmed, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/cms/, role: ROLE_ADMIN }
        #- { path: ^/cms/user/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/mobile/, role: IS_AUTHENTICATED_ANONYMOUSLY }
