<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : src/AppBundle/Proto/ProtobufDocument.proto
 */


namespace AppBundle\Proto;

/**
 * Protobuf message : Proto.HomeDataProto
 */
class HomeDataProto extends \Protobuf\AbstractMessage
{

    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;

    /**
     * @var \Protobuf\Extension\ExtensionFieldMap
     */
    protected $extensions = null;

    /**
     * posts_data optional message = 1
     *
     * @var \AppBundle\Proto\PostsDataProto
     */
    protected $posts_data = null;

    /**
     * ads_data optional message = 2
     *
     * @var \AppBundle\Proto\AdsDataProto
     */
    protected $ads_data = null;

    /**
     * tag_data optional message = 3
     *
     * @var \AppBundle\Proto\TagWithCountDataProto
     */
    protected $tag_data = null;

    /**
     * Check if 'posts_data' has a value
     *
     * @return bool
     */
    public function hasPostsData()
    {
        return $this->posts_data !== null;
    }

    /**
     * Get 'posts_data' value
     *
     * @return \AppBundle\Proto\PostsDataProto
     */
    public function getPostsData()
    {
        return $this->posts_data;
    }

    /**
     * Set 'posts_data' value
     *
     * @param \AppBundle\Proto\PostsDataProto $value
     */
    public function setPostsData(\AppBundle\Proto\PostsDataProto $value = null)
    {
        $this->posts_data = $value;
    }

    /**
     * Check if 'ads_data' has a value
     *
     * @return bool
     */
    public function hasAdsData()
    {
        return $this->ads_data !== null;
    }

    /**
     * Get 'ads_data' value
     *
     * @return \AppBundle\Proto\AdsDataProto
     */
    public function getAdsData()
    {
        return $this->ads_data;
    }

    /**
     * Set 'ads_data' value
     *
     * @param \AppBundle\Proto\AdsDataProto $value
     */
    public function setAdsData(\AppBundle\Proto\AdsDataProto $value = null)
    {
        $this->ads_data = $value;
    }

    /**
     * Check if 'tag_data' has a value
     *
     * @return bool
     */
    public function hasTagData()
    {
        return $this->tag_data !== null;
    }

    /**
     * Get 'tag_data' value
     *
     * @return \AppBundle\Proto\TagWithCountDataProto
     */
    public function getTagData()
    {
        return $this->tag_data;
    }

    /**
     * Set 'tag_data' value
     *
     * @param \AppBundle\Proto\TagWithCountDataProto $value
     */
    public function setTagData(\AppBundle\Proto\TagWithCountDataProto $value = null)
    {
        $this->tag_data = $value;
    }

    /**
     * {@inheritdoc}
     */
    public function extensions()
    {
        if ( $this->extensions !== null) {
            return $this->extensions;
        }

        return $this->extensions = new \Protobuf\Extension\ExtensionFieldMap(__CLASS__);
    }

    /**
     * {@inheritdoc}
     */
    public function unknownFieldSet()
    {
        return $this->unknownFieldSet;
    }

    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
        return new self($stream, $configuration);
    }

    /**
     * {@inheritdoc}
     */
    public static function fromArray(array $values)
    {
        $message = new self();
        $values  = array_merge([
            'posts_data' => null,
            'ads_data' => null,
            'tag_data' => null
        ], $values);

        $message->setPostsData(PostsDataProto::fromArray($values['posts_data']));
        $message->setAdsData(AdsDataProto::fromArray($values['ads_data']));
        $message->setTagData(TagWithCountDataProto::fromArray($values['tag_data']));

        return $message;
    }

    /**
     * {@inheritdoc}
     */
    public static function descriptor()
    {
        return \google\protobuf\DescriptorProto::fromArray([
            'name'      => 'HomeDataProto',
            'field'     => [
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 1,
                    'name' => 'posts_data',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_MESSAGE(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL(),
                    'type_name' => '.Proto.PostsDataProto'
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 2,
                    'name' => 'ads_data',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_MESSAGE(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL(),
                    'type_name' => '.Proto.AdsDataProto'
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 3,
                    'name' => 'tag_data',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_MESSAGE(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL(),
                    'type_name' => '.Proto.TagWithCountDataProto'
                ]),
            ],
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
        $config  = $configuration ?: \Protobuf\Configuration::getInstance();
        $context = $config->createWriteContext();
        $stream  = $context->getStream();

        $this->writeTo($context);
        $stream->seek(0);

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
        $stream      = $context->getStream();
        $writer      = $context->getWriter();
        $sizeContext = $context->getComputeSizeContext();

        if ($this->posts_data !== null) {
            $writer->writeVarint($stream, 10);
            $writer->writeVarint($stream, $this->posts_data->serializedSize($sizeContext));
            $this->posts_data->writeTo($context);
        }

        if ($this->ads_data !== null) {
            $writer->writeVarint($stream, 18);
            $writer->writeVarint($stream, $this->ads_data->serializedSize($sizeContext));
            $this->ads_data->writeTo($context);
        }

        if ($this->tag_data !== null) {
            $writer->writeVarint($stream, 26);
            $writer->writeVarint($stream, $this->tag_data->serializedSize($sizeContext));
            $this->tag_data->writeTo($context);
        }

        if ($this->extensions !== null) {
            $this->extensions->writeTo($context);
        }

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
        $reader = $context->getReader();
        $length = $context->getLength();
        $stream = $context->getStream();

        $limit = ($length !== null)
            ? ($stream->tell() + $length)
            : null;

        while ($limit === null || $stream->tell() < $limit) {

            if ($stream->eof()) {
                break;
            }

            $key  = $reader->readVarint($stream);
            $wire = \Protobuf\WireFormat::getTagWireType($key);
            $tag  = \Protobuf\WireFormat::getTagFieldNumber($key);

            if ($stream->eof()) {
                break;
            }

            if ($tag === 1) {
                \Protobuf\WireFormat::assertWireType($wire, 11);

                $innerSize    = $reader->readVarint($stream);
                $innerMessage = new \AppBundle\Proto\PostsDataProto();

                $this->posts_data = $innerMessage;

                $context->setLength($innerSize);
                $innerMessage->readFrom($context);
                $context->setLength($length);

                continue;
            }

            if ($tag === 2) {
                \Protobuf\WireFormat::assertWireType($wire, 11);

                $innerSize    = $reader->readVarint($stream);
                $innerMessage = new \AppBundle\Proto\AdsDataProto();

                $this->ads_data = $innerMessage;

                $context->setLength($innerSize);
                $innerMessage->readFrom($context);
                $context->setLength($length);

                continue;
            }

            if ($tag === 3) {
                \Protobuf\WireFormat::assertWireType($wire, 11);

                $innerSize    = $reader->readVarint($stream);
                $innerMessage = new \AppBundle\Proto\TagWithCountDataProto();

                $this->tag_data = $innerMessage;

                $context->setLength($innerSize);
                $innerMessage->readFrom($context);
                $context->setLength($length);

                continue;
            }

            $extensions = $context->getExtensionRegistry();
            $extension  = $extensions ? $extensions->findByNumber(__CLASS__, $tag) : null;

            if ($extension !== null) {
                $this->extensions()->add($extension, $extension->readFrom($context, $wire));

                continue;
            }

            if ($this->unknownFieldSet === null) {
                $this->unknownFieldSet = new \Protobuf\UnknownFieldSet();
            }

            $data    = $reader->readUnknown($stream, $wire);
            $unknown = new \Protobuf\Unknown($tag, $wire, $data);

            $this->unknownFieldSet->add($unknown);

        }
    }

    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
        $calculator = $context->getSizeCalculator();
        $size       = 0;

        if ($this->posts_data !== null) {
            $innerSize = $this->posts_data->serializedSize($context);

            $size += 1;
            $size += $innerSize;
            $size += $calculator->computeVarintSize($innerSize);
        }

        if ($this->ads_data !== null) {
            $innerSize = $this->ads_data->serializedSize($context);

            $size += 1;
            $size += $innerSize;
            $size += $calculator->computeVarintSize($innerSize);
        }

        if ($this->tag_data !== null) {
            $innerSize = $this->tag_data->serializedSize($context);

            $size += 1;
            $size += $innerSize;
            $size += $calculator->computeVarintSize($innerSize);
        }

        if ($this->extensions !== null) {
            $size += $this->extensions->serializedSize($context);
        }

        return $size;
    }

    /**
     * {@inheritdoc}
     */
    public function clear()
    {
        $this->posts_data = null;
        $this->ads_data = null;
        $this->tag_data = null;
    }

    /**
     * {@inheritdoc}
     */
    public function merge(\Protobuf\Message $message)
    {
        if ( ! $message instanceof \AppBundle\Proto\HomeDataProto) {
            throw new \InvalidArgumentException(sprintf('Argument 1 passed to %s must be a %s, %s given', __METHOD__, __CLASS__, get_class($message)));
        }

        $this->posts_data = ($message->posts_data !== null) ? $message->posts_data : $this->posts_data;
        $this->ads_data = ($message->ads_data !== null) ? $message->ads_data : $this->ads_data;
        $this->tag_data = ($message->tag_data !== null) ? $message->tag_data : $this->tag_data;
    }


}

