<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : src/AppBundle/Proto/ProtobufDocument.proto
 */


namespace AppBundle\Proto;

/**
 * Protobuf message : Proto.MetaProto
 */
class MetaProto extends \Protobuf\AbstractMessage
{

    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;

    /**
     * @var \Protobuf\Extension\ExtensionFieldMap
     */
    protected $extensions = null;

    /**
     * fb_total_likes optional int32 = 1
     *
     * @var int
     */
    protected $fb_total_likes = null;

    /**
     * fb_total_comments optional int32 = 2
     *
     * @var int
     */
    protected $fb_total_comments = null;

    /**
     * Check if 'fb_total_likes' has a value
     *
     * @return bool
     */
    public function hasFbTotalLikes()
    {
        return $this->fb_total_likes !== null;
    }

    /**
     * Get 'fb_total_likes' value
     *
     * @return int
     */
    public function getFbTotalLikes()
    {
        return $this->fb_total_likes;
    }

    /**
     * Set 'fb_total_likes' value
     *
     * @param int $value
     */
    public function setFbTotalLikes($value = null)
    {
        $this->fb_total_likes = $value;
    }

    /**
     * Check if 'fb_total_comments' has a value
     *
     * @return bool
     */
    public function hasFbTotalComments()
    {
        return $this->fb_total_comments !== null;
    }

    /**
     * Get 'fb_total_comments' value
     *
     * @return int
     */
    public function getFbTotalComments()
    {
        return $this->fb_total_comments;
    }

    /**
     * Set 'fb_total_comments' value
     *
     * @param int $value
     */
    public function setFbTotalComments($value = null)
    {
        $this->fb_total_comments = $value;
    }

    /**
     * {@inheritdoc}
     */
    public function extensions()
    {
        if ( $this->extensions !== null) {
            return $this->extensions;
        }

        return $this->extensions = new \Protobuf\Extension\ExtensionFieldMap(__CLASS__);
    }

    /**
     * {@inheritdoc}
     */
    public function unknownFieldSet()
    {
        return $this->unknownFieldSet;
    }

    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
        return new self($stream, $configuration);
    }

    /**
     * {@inheritdoc}
     */
    public static function fromArray(array $values)
    {
        $message = new self();
        $values  = array_merge([
            'fb_total_likes' => null,
            'fb_total_comments' => null
        ], $values);

        $message->setFbTotalLikes($values['fb_total_likes']);
        $message->setFbTotalComments($values['fb_total_comments']);

        return $message;
    }

    /**
     * {@inheritdoc}
     */
    public static function descriptor()
    {
        return \google\protobuf\DescriptorProto::fromArray([
            'name'      => 'MetaProto',
            'field'     => [
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 1,
                    'name' => 'fb_total_likes',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_INT32(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 2,
                    'name' => 'fb_total_comments',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_INT32(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
            ],
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
        $config  = $configuration ?: \Protobuf\Configuration::getInstance();
        $context = $config->createWriteContext();
        $stream  = $context->getStream();

        $this->writeTo($context);
        $stream->seek(0);

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
        $stream      = $context->getStream();
        $writer      = $context->getWriter();
        $sizeContext = $context->getComputeSizeContext();

        if ($this->fb_total_likes !== null) {
            $writer->writeVarint($stream, 8);
            $writer->writeVarint($stream, $this->fb_total_likes);
        }

        if ($this->fb_total_comments !== null) {
            $writer->writeVarint($stream, 16);
            $writer->writeVarint($stream, $this->fb_total_comments);
        }

        if ($this->extensions !== null) {
            $this->extensions->writeTo($context);
        }

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
        $reader = $context->getReader();
        $length = $context->getLength();
        $stream = $context->getStream();

        $limit = ($length !== null)
            ? ($stream->tell() + $length)
            : null;

        while ($limit === null || $stream->tell() < $limit) {

            if ($stream->eof()) {
                break;
            }

            $key  = $reader->readVarint($stream);
            $wire = \Protobuf\WireFormat::getTagWireType($key);
            $tag  = \Protobuf\WireFormat::getTagFieldNumber($key);

            if ($stream->eof()) {
                break;
            }

            if ($tag === 1) {
                \Protobuf\WireFormat::assertWireType($wire, 5);

                $this->fb_total_likes = $reader->readVarint($stream);

                continue;
            }

            if ($tag === 2) {
                \Protobuf\WireFormat::assertWireType($wire, 5);

                $this->fb_total_comments = $reader->readVarint($stream);

                continue;
            }

            $extensions = $context->getExtensionRegistry();
            $extension  = $extensions ? $extensions->findByNumber(__CLASS__, $tag) : null;

            if ($extension !== null) {
                $this->extensions()->add($extension, $extension->readFrom($context, $wire));

                continue;
            }

            if ($this->unknownFieldSet === null) {
                $this->unknownFieldSet = new \Protobuf\UnknownFieldSet();
            }

            $data    = $reader->readUnknown($stream, $wire);
            $unknown = new \Protobuf\Unknown($tag, $wire, $data);

            $this->unknownFieldSet->add($unknown);

        }
    }

    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
        $calculator = $context->getSizeCalculator();
        $size       = 0;

        if ($this->fb_total_likes !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->fb_total_likes);
        }

        if ($this->fb_total_comments !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->fb_total_comments);
        }

        if ($this->extensions !== null) {
            $size += $this->extensions->serializedSize($context);
        }

        return $size;
    }

    /**
     * {@inheritdoc}
     */
    public function clear()
    {
        $this->fb_total_likes = null;
        $this->fb_total_comments = null;
    }

    /**
     * {@inheritdoc}
     */
    public function merge(\Protobuf\Message $message)
    {
        if ( ! $message instanceof \AppBundle\Proto\MetaProto) {
            throw new \InvalidArgumentException(sprintf('Argument 1 passed to %s must be a %s, %s given', __METHOD__, __CLASS__, get_class($message)));
        }

        $this->fb_total_likes = ($message->fb_total_likes !== null) ? $message->fb_total_likes : $this->fb_total_likes;
        $this->fb_total_comments = ($message->fb_total_comments !== null) ? $message->fb_total_comments : $this->fb_total_comments;
    }


}

