<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : src/AppBundle/Proto/ProtobufDocument.proto
 */


namespace AppBundle\Proto;

/**
 * Protobuf message : Proto.TagProto
 */
class TagProto extends \Protobuf\AbstractMessage
{

    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;

    /**
     * @var \Protobuf\Extension\ExtensionFieldMap
     */
    protected $extensions = null;

    /**
     * key optional string = 1
     *
     * @var string
     */
    protected $key = null;

    /**
     * name_chi optional string = 2
     *
     * @var string
     */
    protected $name_chi = null;

    /**
     * name_eng optional string = 3
     *
     * @var string
     */
    protected $name_eng = null;

    /**
     * image_link optional string = 4
     *
     * @var string
     */
    protected $image_link = null;

    /**
     * Check if 'key' has a value
     *
     * @return bool
     */
    public function hasKey()
    {
        return $this->key !== null;
    }

    /**
     * Get 'key' value
     *
     * @return string
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * Set 'key' value
     *
     * @param string $value
     */
    public function setKey($value = null)
    {
        $this->key = $value;
    }

    /**
     * Check if 'name_chi' has a value
     *
     * @return bool
     */
    public function hasNameChi()
    {
        return $this->name_chi !== null;
    }

    /**
     * Get 'name_chi' value
     *
     * @return string
     */
    public function getNameChi()
    {
        return $this->name_chi;
    }

    /**
     * Set 'name_chi' value
     *
     * @param string $value
     */
    public function setNameChi($value = null)
    {
        $this->name_chi = $value;
    }

    /**
     * Check if 'name_eng' has a value
     *
     * @return bool
     */
    public function hasNameEng()
    {
        return $this->name_eng !== null;
    }

    /**
     * Get 'name_eng' value
     *
     * @return string
     */
    public function getNameEng()
    {
        return $this->name_eng;
    }

    /**
     * Set 'name_eng' value
     *
     * @param string $value
     */
    public function setNameEng($value = null)
    {
        $this->name_eng = $value;
    }

    /**
     * Check if 'image_link' has a value
     *
     * @return bool
     */
    public function hasImageLink()
    {
        return $this->image_link !== null;
    }

    /**
     * Get 'image_link' value
     *
     * @return string
     */
    public function getImageLink()
    {
        return $this->image_link;
    }

    /**
     * Set 'image_link' value
     *
     * @param string $value
     */
    public function setImageLink($value = null)
    {
        $this->image_link = $value;
    }

    /**
     * {@inheritdoc}
     */
    public function extensions()
    {
        if ( $this->extensions !== null) {
            return $this->extensions;
        }

        return $this->extensions = new \Protobuf\Extension\ExtensionFieldMap(__CLASS__);
    }

    /**
     * {@inheritdoc}
     */
    public function unknownFieldSet()
    {
        return $this->unknownFieldSet;
    }

    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
        return new self($stream, $configuration);
    }

    /**
     * {@inheritdoc}
     */
    public static function fromArray(array $values)
    {
        $message = new self();
        $values  = array_merge([
            'key' => null,
            'name_chi' => null,
            'name_eng' => null,
            'image_link' => null
        ], $values);

        $message->setKey($values['key']);
        $message->setNameChi($values['name_chi']);
        $message->setNameEng($values['name_eng']);
        $message->setImageLink($values['image_link']);

        return $message;
    }

    /**
     * {@inheritdoc}
     */
    public static function descriptor()
    {
        return \google\protobuf\DescriptorProto::fromArray([
            'name'      => 'TagProto',
            'field'     => [
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 1,
                    'name' => 'key',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_STRING(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 2,
                    'name' => 'name_chi',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_STRING(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 3,
                    'name' => 'name_eng',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_STRING(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 4,
                    'name' => 'image_link',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_STRING(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
            ],
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
        $config  = $configuration ?: \Protobuf\Configuration::getInstance();
        $context = $config->createWriteContext();
        $stream  = $context->getStream();

        $this->writeTo($context);
        $stream->seek(0);

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
        $stream      = $context->getStream();
        $writer      = $context->getWriter();
        $sizeContext = $context->getComputeSizeContext();

        if ($this->key !== null) {
            $writer->writeVarint($stream, 10);
            $writer->writeString($stream, $this->key);
        }

        if ($this->name_chi !== null) {
            $writer->writeVarint($stream, 18);
            $writer->writeString($stream, $this->name_chi);
        }

        if ($this->name_eng !== null) {
            $writer->writeVarint($stream, 26);
            $writer->writeString($stream, $this->name_eng);
        }

        if ($this->image_link !== null) {
            $writer->writeVarint($stream, 34);
            $writer->writeString($stream, $this->image_link);
        }

        if ($this->extensions !== null) {
            $this->extensions->writeTo($context);
        }

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
        $reader = $context->getReader();
        $length = $context->getLength();
        $stream = $context->getStream();

        $limit = ($length !== null)
            ? ($stream->tell() + $length)
            : null;

        while ($limit === null || $stream->tell() < $limit) {

            if ($stream->eof()) {
                break;
            }

            $key  = $reader->readVarint($stream);
            $wire = \Protobuf\WireFormat::getTagWireType($key);
            $tag  = \Protobuf\WireFormat::getTagFieldNumber($key);

            if ($stream->eof()) {
                break;
            }

            if ($tag === 1) {
                \Protobuf\WireFormat::assertWireType($wire, 9);

                $this->key = $reader->readString($stream);

                continue;
            }

            if ($tag === 2) {
                \Protobuf\WireFormat::assertWireType($wire, 9);

                $this->name_chi = $reader->readString($stream);

                continue;
            }

            if ($tag === 3) {
                \Protobuf\WireFormat::assertWireType($wire, 9);

                $this->name_eng = $reader->readString($stream);

                continue;
            }

            if ($tag === 4) {
                \Protobuf\WireFormat::assertWireType($wire, 9);

                $this->image_link = $reader->readString($stream);

                continue;
            }

            $extensions = $context->getExtensionRegistry();
            $extension  = $extensions ? $extensions->findByNumber(__CLASS__, $tag) : null;

            if ($extension !== null) {
                $this->extensions()->add($extension, $extension->readFrom($context, $wire));

                continue;
            }

            if ($this->unknownFieldSet === null) {
                $this->unknownFieldSet = new \Protobuf\UnknownFieldSet();
            }

            $data    = $reader->readUnknown($stream, $wire);
            $unknown = new \Protobuf\Unknown($tag, $wire, $data);

            $this->unknownFieldSet->add($unknown);

        }
    }

    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
        $calculator = $context->getSizeCalculator();
        $size       = 0;

        if ($this->key !== null) {
            $size += 1;
            $size += $calculator->computeStringSize($this->key);
        }

        if ($this->name_chi !== null) {
            $size += 1;
            $size += $calculator->computeStringSize($this->name_chi);
        }

        if ($this->name_eng !== null) {
            $size += 1;
            $size += $calculator->computeStringSize($this->name_eng);
        }

        if ($this->image_link !== null) {
            $size += 1;
            $size += $calculator->computeStringSize($this->image_link);
        }

        if ($this->extensions !== null) {
            $size += $this->extensions->serializedSize($context);
        }

        return $size;
    }

    /**
     * {@inheritdoc}
     */
    public function clear()
    {
        $this->key = null;
        $this->name_chi = null;
        $this->name_eng = null;
        $this->image_link = null;
    }

    /**
     * {@inheritdoc}
     */
    public function merge(\Protobuf\Message $message)
    {
        if ( ! $message instanceof \AppBundle\Proto\TagProto) {
            throw new \InvalidArgumentException(sprintf('Argument 1 passed to %s must be a %s, %s given', __METHOD__, __CLASS__, get_class($message)));
        }

        $this->key = ($message->key !== null) ? $message->key : $this->key;
        $this->name_chi = ($message->name_chi !== null) ? $message->name_chi : $this->name_chi;
        $this->name_eng = ($message->name_eng !== null) ? $message->name_eng : $this->name_eng;
        $this->image_link = ($message->image_link !== null) ? $message->image_link : $this->image_link;
    }


}

